# Generated by Django 6.0.4 on 2026-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airspotteruser',
            name='favorite_sightings',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='sightings.sighting'),
        ),
    ]
