# Generated by Django 6.0.4 on 2026-04-11 14:47

import aviation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icao_code', models.CharField(max_length=4, unique=True, validators=[aviation.models.validate_icao_code])),
                ('iata_code', models.CharField(max_length=3, unique=True, validators=[aviation.models.validate_iata_code])),
                ('country', models.CharField(max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icao_code', models.CharField(max_length=4, unique=True, validators=[aviation.models.validate_icao_code])),
                ('iata_code', models.CharField(max_length=3, unique=True, validators=[aviation.models.validate_iata_code])),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('aircraft_type', models.CharField(max_length=50)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='aviation.airline')),
            ],
            options={
                'ordering': ('registration',),
            },
        ),
    ]
