# Generated by Django 6.0.4 on 2026-04-14 19:47

import aviation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(max_length=2, unique=True, validators=[aviation.models.validate_airline_iata_code]),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao_code',
            field=models.CharField(max_length=3, unique=True, validators=[aviation.models.validate_airline_icao_code]),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, unique=True, validators=[aviation.models.validate_airport_iata_code]),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(max_length=4, unique=True, validators=[aviation.models.validate_airport_icao_code]),
        ),
    ]
